BlogWebApplication/Entities/BaseEntity.cs
namespace BlogWebApplication.Entities
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

BlogWebApplication/Entities/Project.cs
namespace BlogWebApplication.Entities
{
    public class Project : BaseEntity
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

BlogWebApplication/Models/ErrorViewModel.cs
namespace BlogWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogWebApplication/Controllers/HomeController.cs
using BlogWebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogWebApplication.Controllers
{
    [Route("home")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [Route("~/")]
        [Route("")]
        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }
        [Route("privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogWebApplication/Controllers/ProjectController.cs
using BlogWebApplication.Dtos;
using BlogWebApplication.Models;
using BlogWebApplication.Services.Contract;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogWebApplication.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;

        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }

        // GET: ProjectController
        public ActionResult Index()
        {
            var projects = _projectService.GetProjects(1);
            return View(projects);
        }

        // GET: ProjectController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProjectController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(ProjectDto project)
        {
            try
            {
                _projectService.AddProject(project);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

BlogWebApplication/Views/Home/Index.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Home Section -->

<section id="home" class="main-home parallax-section">
     <div class="overlay"></div>
     <div id="particles-js"></div>
     <div class="container">
          <div class="row">

               <div class="col-md-12 col-sm-12">
                    <h1>Hello! This is Neuron.</h1>
                    <h4>Responsive Blog HTML CSS Website Template</h4>
                    <a href="#blog" class="smoothScroll btn btn-default">Discover More</a>
               </div>

          </div>
     </div>
</section>

<!-- Blog Section -->

<section id="blog">
     <div class="container">
          <div class="row">

               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a asp-controller="singlepost" asp-action="index">
                                   <img src="~/user/images/blog-image1.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a asp-controller="singlepost" asp-action="index">We Help You Create Perfect Modern Design</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="~/user/images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> July 22, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 35 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a asp-controller="singlepost" asp-action="index" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a asp-controller="singlepost" asp-action="index">
                                   <img src="~/user/images/blog-image2.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a asp-controller="singlepost" asp-action="index">In pretium tellus et ante accumsan</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="~/user/images/author-image2.jpg" class="img-responsive img-circle"> Leo Dennis</a></span>
                              <span><i class="fa fa-date"></i> June 10, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 48 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a asp-controller="singlepost" asp-action="index" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-video">
                              <div class="embed-responsive embed-responsive-16by9">
                                   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Pgmx7z49OEk" allowfullscreen></iframe>
                              </div>
                         </div>
                         <div class="blog-post-title">
                              <h3><a asp-controller="singlepost" asp-action="index">Nam interdum maximus dolor faucibus</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="~/user/images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> May 30, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 63 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a asp-controller="singlepost" asp-action="index" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a asp-controller="singlepost" asp-action="index">
                                   <img src="~/user/images/blog-image3.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a asp-controller="singlepost" asp-action="index">The ingredients that make a great burger</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="~/user/images/author-image2.jpg" class="img-responsive img-circle"> Leo Dennis</a></span>
                              <span><i class="fa fa-date"></i> April 18, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 124 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a asp-controller="singlepost" asp-action="index" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>

                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a asp-controller="singlepost" asp-action="index">
                                   <img src="~/user/images/blog-image4.jpg" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a asp-controller="singlepost" asp-action="index">Vestibulum vel mauris nec ex tempus</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="~/user/images/author-image1.jpg" class="img-responsive img-circle"> Jen Lopez</a></span>
                              <span><i class="fa fa-date"></i> March 12, 2017</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i> 256 Comments</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                              <a asp-controller="singlepost" asp-action="index" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>
               </div>

          </div>
     </div>
</section>

BlogWebApplication/Views/Project/Create.cshtml
@model ProjectDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProjectDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
@using (Html.BeginForm("Create", "Project", FormMethod.Post))
    {            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name: </label>
                    @Html.TextBoxFor(m => m.Name)
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description: </label>
                    @Html.TextBoxFor(m => m.Description)
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary" >Create</button>
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogWebApplication/Views/Project/Index.cshtml
@model IEnumerable<ProjectDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
}
    </tbody>
</table>

BlogWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<title>Cục Vịt HTML CSS Template</title>
	<!--

	Template 2085 Neuron

	http://www.tooplate.com/view/2085-neuron

	-->
	<link rel="stylesheet" href="~/user/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/user/css/font-awesome.min.css">

	<!-- Main css -->
	<link rel="stylesheet" href="~/user/css/style.css">
	<link href="https://fonts.googleapis.com/css?family=Lora|Merriweather:300,400" rel="stylesheet">

</head>
<body>

	<!-- PRE LOADER -->

	@*<div class="preloader">
		<div class="sk-spinner sk-spinner-wordpress">
			<span class="sk-inner-circle"></span>
		</div>
	</div>*@

	<!-- Navigation section  -->

	<div class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">

			<div class="navbar-header">
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
				</button>
				<a asp-controller="home" asp-acion="index" class="navbar-brand">Cục Vịt</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><a asp-controller="home" asp-action="index">Home</a></li>
					<li><a asp-controller="about" asp-action="index">About</a></li>
					<li><a asp-controller="gallery" asp-action="index">Gallery</a></li>
					<li><a asp-controller="contact" asp-action="index">Contact</a></li>
				</ul>
			</div>

		</div>
	</div>
	@RenderBody()

	<footer>
		<div class="container">
			<div class="row">

				<div class="col-md-5 col-md-offset-1 col-sm-6">
					<h3>Neuron Studio</h3>
					<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
					<div class="footer-copyright">
						<p>Copyright &copy; 2017 Your Company - Design: Tooplate</p>
					</div>
				</div>

				<div class="col-md-4 col-md-offset-1 col-sm-6">
					<h3>Talk to us</h3>
					<p><i class="fa fa-globe"></i> 512 Delicious Street, San Francisco, CA 10880</p>
					<p><i class="fa fa-phone"></i> 010-020-0990</p>
					<p><i class="fa fa-save"></i> info@company.com</p>
				</div>

				<div class="clearfix col-md-12 col-sm-12">
					<hr>
				</div>

				<div class="col-md-12 col-sm-12">
					<ul class="social-icon">
						<li><a href="#" class="fa fa-facebook"></a></li>
						<li><a href="#" class="fa fa-twitter"></a></li>
						<li><a href="#" class="fa fa-google-plus"></a></li>
						<li><a href="#" class="fa fa-dribbble"></a></li>
						<li><a href="#" class="fa fa-linkedin"></a></li>
					</ul>
				</div>

			</div>
		</div>
	</footer>

	<!-- Back top -->
	<a href="#back-top" class="go-top"><i class="fa fa-angle-up"></i></a>

	<!-- SCRIPTS -->

	<script href="~/user/js/jquery.js"></script>
	<script href="~/user/js/bootstrap.min.js"></script>
	<script href="~/user/js/particles.min.js"></script>
	<script href="~/user/js/app.js"></script>
	<script href="~/user/js/jquery.parallax.js"></script>
	<script href="~/user/js/smoothscroll.js"></script>
	<script href="~/user/js/custom.js"></script>

</body>
</html>